images:
  registry:
    hostname: 660990364978.dkr.ecr.ap-northeast-1.amazonaws.com
  name:
    nginx:
      repo: makoto-my-nginx
  pullPolicy: IfNotPresent

nginx:
  hostname: nginx.aws.cci2.makotom.net
  certARN: arn:aws:acm:ap-northeast-1:660990364978:certificate/58bfea96-73aa-4aec-a492-96df031c83fd

replicaCount: 1

podAnnotations: {} # Leaving empty; just defined for possible future use

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi
