apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-nginx
  labels:
    app: my-nginx
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: my-nginx
  template:
    metadata:
      labels:
        app: my-nginx
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      {{ if .Values.images.registry.secrets }}
      imagePullSecrets:
        - name: {{ .Values.images.registry.secrets }}
      {{ end }}
      containers:
        - name: my-nginx
          image: "{{ .Values.images.registry.hostname }}/{{ .Values.images.name.nginx.repo }}:{{ .Values.images.name.nginx.tag }}"
          imagePullPolicy: {{ .Values.images.pullPolicy }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /version.txt
              port: http
          readinessProbe:
            httpGet:
              path: /version.txt
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
