apiVersion: v1
kind: Service
metadata:
  name: my-nginx
  labels:
    app: my-nginx
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: http
    service.beta.kubernetes.io/aws-load-balancer-ssl-cert: {{ .Values.nginx.certARN }}
    service.beta.kubernetes.io/aws-load-balancer-ssl-ports: my-nginx-https
    service.beta.kubernetes.io/aws-load-balancer-additional-resource-tags: Name=my-nginx,Owner=makotom
    external-dns.alpha.kubernetes.io/hostname: {{ .Values.nginx.hostname }}
spec:
  type: LoadBalancer
  ports:
    - port: 443
      targetPort: 80
      protocol: TCP
      name: my-nginx-https
  selector:
    app: my-nginx
